version: '3'

services:
  pgsql:
    image: postgres
    ports:
      - ${PG_PORT}:5432
    environment:
      PG_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      TZ: 'Europe/Paris'
    volumes:
      - ./docker/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  redis:
    image: redis:alpine
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./db-redis:/data

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
