name: Build, test and deploy
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    name: '🧐 - Lint'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

  tests:
    name: '🧪 - Tests'
    runs-on: ubuntu-latest
    needs: [lint]
    strategy:
      matrix:
        node-version: [16.x]
    env:
      DB_NAME: papote_car_test
      DB_USER: papote_car_user
      DB_PASSWORD: papote_car_password

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '13'
          postgresql db: ${{env.DB_NAME}}
          postgresql user: ${{env.DB_USER}}
          postgresql password: ${{env.DB_PASSWORD}}

      - name: Start Redis
        uses: supercharge/redis-github-action@1.5.0
        with:
          redis-version: 7

      - run: npm ci
      - run: npm run coverage
        env:
          PORT: 3000
          HOST: 0.0.0.0
          APP_KEY: ${{ secrets.APP_KEY_TESTING }}
          DRIVE_DISK: local
          DB_CONNECTION: pg
          PG_HOST: localhost
          PG_PORT: 5432
          PG_USER: ${{env.DB_USER}}
          PG_PASSWORD: ${{env.DB_PASSWORD}}
          PG_DB_NAME: ${{env.DB_NAME}}
          REDIS_CONNECTION: local
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          PUSHER_APP_ID: ${{ secrets.PUSHER_APP_ID }}
          PUSHER_APP_KEY: ${{ secrets.PUSHER_APP_KEY }}
          PUSHER_APP_SECRET: ${{ secrets.PUSHER_APP_SECRET }}
          SMTP_HOST: fake.smtp.fr
          SMTP_PORT: 25
          SMTP_USERNAME: fakemail@mail.com
          SMTP_PASSWORD: fakepassword
